
project_id = "acnympbxfptajtxvmkqn"

[functions.proxy-pdf]
verify_jwt = false

[functions.fetch-books]
verify_jwt = true

[functions.fetch-videos]
verify_jwt = true

[functions.fetch-podcasts]
verify_jwt = true

[functions.fetch-biblioteca]
verify_jwt = true

[functions.recent-additions-rotation]
verify_jwt = false
